//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.16 at 06:41:57 PM EEST 
//


package deposit;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import java.math.BigDecimal;


/**
 * <p>Java class for deposit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="deposit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="depositor" type="{}depositor"/>
 *         &lt;element name="account-id" type="{}accountId"/>
 *         &lt;element ref="{www.example.org/xmlns/financial}amount-on-deposit"/>
 *         &lt;element ref="{www.example.org/xmlns/financial}interest"/>
 *         &lt;element name="time-constraint" type="{}timeConstraint"/>
 *       &lt;/all>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="type" type="{}type" />
 *       &lt;attribute ref="{www.example.org/xmlns/bank}name"/>
 *       &lt;attribute name="country" type="{http://www.codesynthesis.com/xmlns/xsstl}ISO3166CountryCode" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deposit", propOrder = {

})
public class Deposit {

    @XmlElement(required = true)
    protected String depositor;
    @XmlElement(name = "account-id")
    protected int accountId;
    @XmlElement(name = "amount-on-deposit", namespace = "www.example.org/xmlns/financial", required = true)
    protected BigDecimal amountOnDeposit;
    @XmlElement(namespace = "www.example.org/xmlns/financial", required = true)
    protected BigDecimal interest;
    @XmlElement(name = "time-constraint")
    @XmlSchemaType(name = "unsignedInt")
    protected long timeConstraint;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "type")
    protected Type type;
    @XmlAttribute(name = "name", namespace = "www.example.org/xmlns/bank")
    protected String name;
    @XmlAttribute(name = "country")
    protected ISO3166CountryCode country;

    /**
     * Gets the value of the depositor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositor() {
        return depositor;
    }

    /**
     * Sets the value of the depositor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositor(String value) {
        this.depositor = value;
    }

    /**
     * Gets the value of the accountId property.
     * 
     */
    public int getAccountId() {
        return accountId;
    }

    /**
     * Sets the value of the accountId property.
     * 
     */
    public void setAccountId(int value) {
        this.accountId = value;
    }

    /**
     * Gets the value of the amountOnDeposit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountOnDeposit() {
        return amountOnDeposit;
    }

    /**
     * Sets the value of the amountOnDeposit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountOnDeposit(BigDecimal value) {
        this.amountOnDeposit = value;
    }

    /**
     * Gets the value of the interest property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInterest() {
        return interest;
    }

    /**
     * Sets the value of the interest property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInterest(BigDecimal value) {
        this.interest = value;
    }

    /**
     * Gets the value of the timeConstraint property.
     * 
     */
    public long getTimeConstraint() {
        return timeConstraint;
    }

    /**
     * Sets the value of the timeConstraint property.
     * 
     */
    public void setTimeConstraint(long value) {
        this.timeConstraint = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Type }
     *     
     */
    public Type getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Type }
     *     
     */
    public void setType(Type value) {
        this.type = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link ISO3166CountryCode }
     *     
     */
    public ISO3166CountryCode getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISO3166CountryCode }
     *     
     */
    public void setCountry(ISO3166CountryCode value) {
        this.country = value;
    }

    @Override
    public String toString() {
        return "Deposit{\n" +
                "\tdepositor: " + depositor +
                "\n\taccountId: " + accountId +
                "\n\tamountOnDeposit: " + amountOnDeposit +
                "\n\tinterest: " + interest +
                "\n\ttimeConstraint: " + timeConstraint +
                "\n\tid: " + id +
                "\n\ttype: " + type +
                "\n\tname: " + name +
                "\n\tcountry: " + country +
                "\n}";
    }
}
